SMMC/SMMC/Controllers/MusicClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SMMC.Models;
using SMMC.ViewModels;

namespace SMMC.Controllers
{
    public class MusicClassesController : Controller
    {
        private readonly IN705_2018S2_db3shared01Context _context;

        public MusicClassesController(IN705_2018S2_db3shared01Context context)
        {
            _context = context;
        }

        // GET: MusicClasses
        public async Task<IActionResult> Index()
        {
            var IN705_2018S2_db3shared01Context = _context.EnrollmentMusicClass
                .Include(m => m.MusicClass)
                    .ThenInclude(l => l.LessonTime)
                .Include(m => m.Enrollment)
                    .ThenInclude(e => e.Instrument)
                .Include(m => m.MusicClass)
                    .ThenInclude(t => t.Tutor.Staff.Person).GroupBy(e => e.MusicClassId).Select(g=>g.First());
            
            
            
            //.MusicClass
            //    .Include(m => m.LessonTime)
            //    .Include(m => m.Tutor.Staff.Person)
            //    .Include(m=>m.EnrollmentMusicClass)
            //    .Include(m=>m.Tutor.TutorType);

            


            return View(await IN705_2018S2_db3shared01Context.ToListAsync());
        }

        // GET: MusicClasses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var students = _context.EnrollmentMusicClass
                .Where(emc => emc.MusicClassId == id)
                .Include(e => e.Enrollment.Instrument)
                .Include(e => e.Enrollment.Student.Person)
                .Include(e=>e.MusicClass.Tutor.Staff.Person)
                .ToList();
            

            ViewBag.Grade = students.First().Enrollment.Grade;
            ViewBag.Instrument = students.First().Enrollment.Instrument.Instrument1;
           

            var musicClass = await _context.MusicClass
                .Include(m => m.LessonTime)
                .Include(m => m.Tutor)                
                .FirstOrDefaultAsync(m => m.MusicClassId == id); 
                
            if (musicClass == null)
            {
                return NotFound();
            }

            //ViewData["test"] = new SelectList(s);
            return View(musicClass);
        }

        // GET: MusicClasses/Create
        public IActionResult Create()
        {
            ViewData["LessonTimeId"] = new SelectList(_context.LessonTime, "LessonTimeId", "LessonTimeId");
            ViewData["TutorId"] = new SelectList(_context.Tutor, "TutorId", "TutorId");
            return View();
        }

        // POST: MusicClasses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MusicClassId,TutorId,LessonTimeId,StartDate,EndDate")] MusicClass musicClass)
        {
            if (ModelState.IsValid)
            {
                _context.Add(musicClass);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LessonTimeId"] = new SelectList(_context.LessonTime, "LessonTimeId", "LessonTimeId", musicClass.LessonTimeId);
            ViewData["TutorId"] = new SelectList(_context.Tutor, "TutorId", "TutorId", musicClass.TutorId);
            return View(musicClass);
        }

        // GET: MusicClasses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var musicClass = await _context.MusicClass.FindAsync(id);
            if (musicClass == null)
            {
                return NotFound();
            }

            var students = _context.EnrollmentMusicClass
                .Where(emc => emc.MusicClassId == id)
                .Include(e => e.Enrollment.Instrument)
                .Include(e => e.Enrollment.Student.Person)
                .Include(e => e.MusicClass.Tutor.Staff.Person)
                .ToList();


            List<Tutor> tutors = _context.Tutor.Include(a => a.Staff.Person).ToList();

            List<TutorViewModel> t = tutors.Select(s => new TutorViewModel
            {
                id = s.TutorId,
                name = s.Staff.Person.FirstName + " " + s.Staff.Person.LastName

            }).ToList();

            ViewData["LessonTimeId"] = new SelectList(_context.LessonTime, "LessonTimeId", "Time", musicClass.LessonTimeId);
            ViewData["TutorId"] = new SelectList(t, "id", "name", musicClass.TutorId);
            return View(musicClass);
        }

        // POST: MusicClasses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MusicClassId,TutorId,LessonTimeId,StartDate,EndDate")] MusicClass mc)
        {
            var musicClass = await _context.MusicClass
               .Include(m => m.LessonTime)
               .Include(m => m.Tutor)
               .FirstOrDefaultAsync(m => m.MusicClassId == id);

            musicClass.LessonTimeId = mc.LessonTimeId;
            musicClass.TutorId = mc.TutorId;


            if (id != musicClass.MusicClassId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(musicClass);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MusicClassExists(musicClass.MusicClassId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LessonTimeId"] = new SelectList(_context.LessonTime, "LessonTimeId", "LessonTimeId", musicClass.LessonTimeId);
            ViewData["TutorId"] = new SelectList(_context.Tutor, "TutorId", "TutorId", musicClass.TutorId);
            return View(musicClass);
        }

        // GET: MusicClasses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var musicClass = await _context.MusicClass
                .Include(m => m.LessonTime)
                .Include(m => m.Tutor)
                .FirstOrDefaultAsync(m => m.MusicClassId == id);
            if (musicClass == null)
            {
                return NotFound();
            }

            return View(musicClass);
        }

        // POST: MusicClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var musicClass = await _context.MusicClass.FindAsync(id);
            _context.MusicClass.Remove(musicClass);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteStudent(int id1, int id2)
        {
            var enrollmentMusicClass = await _context.EnrollmentMusicClass
                .Include(e => e.Enrollment)
                .Include(e => e.MusicClass)
                .FirstOrDefaultAsync(m => m.EnrollmentId == id1 && m.MusicClassId == id2);
            if (enrollmentMusicClass == null)
            {
                return NotFound();
            }

            return View(enrollmentMusicClass);
        }

        // POST: EnrollmentMusicClasses/Delete/5
        [HttpPost, ActionName("DeleteStudent")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteStudentConfirmed()
        {
            int id1 = Convert.ToInt32(Request.Form["EnrollmentID"]);
            int id2 = Convert.ToInt32(Request.Form["MusicClassID"]);

            var enrollmentMusicClass = await _context.EnrollmentMusicClass
                .Include(e => e.Enrollment)
                .Include(e => e.MusicClass)
                .FirstOrDefaultAsync(m => m.EnrollmentId == id1 && m.MusicClassId == id2);

            _context.EnrollmentMusicClass.Remove(enrollmentMusicClass);
            await _context.SaveChangesAsync();
            return RedirectToAction("Edit", new { id = enrollmentMusicClass.MusicClassId });
        }


        private bool MusicClassExists(int id)
        {
            return _context.MusicClass.Any(e => e.MusicClassId == id);
        }
    }
}

SMMC/SMMC/Views/MusicClasses/Create.cshtml
@model SMMC.Models.MusicClass

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>MusicClass</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TutorId" class="control-label"></label>
                <select asp-for="TutorId" class ="form-control" asp-items="ViewBag.TutorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="LessonTimeId" class="control-label"></label>
                <select asp-for="LessonTimeId" class ="form-control" asp-items="ViewBag.LessonTimeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SMMC/SMMC/Views/MusicClasses/Delete.cshtml
@model SMMC.Models.MusicClass

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MusicClass</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LessonTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LessonTime.LessonTimeId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Tutor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tutor.TutorId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MusicClassId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SMMC/SMMC/Views/MusicClasses/DeleteStudent.cshtml
@model SMMC.Models.EnrollmentMusicClass

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EnrollmentMusicClass</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Enrollment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Enrollment.EnrollmentId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MusicClass)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MusicClass.MusicClassId)
        </dd>
    </dl>
    
    <form asp-action="DeleteStudent">
        <input type="hidden" asp-for="EnrollmentId" />
        <input type="hidden" asp-for="MusicClassId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SMMC/SMMC/Views/MusicClasses/Details.cshtml
@model SMMC.Models.MusicClass

@{
    ViewData["Title"] = "Details";
}





<h2>Class Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Instrument: @ViewBag.Instrument
        </dt>
        <dd>
            
        </dd>
        <dt>
            Grade: @ViewBag.Grade
        </dt>
        <dd>
            
        </dd>
        <dt>
            Start Date: @Model.StartDate.ToShortDateString()
        </dt>
        <dd>
            
        </dd>
        <dt>
            End Date:  @Model.EndDate.ToShortDateString()
        </dt>
        <dd>
            
        </dd>
        <dt>
            Lesson Time: @Html.DisplayFor(model => model.LessonTime.Time)
        </dt>
        <dd>
            
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Tutor): @Html.DisplayFor(model => model.Tutor.Staff.Person.FirstName)
            @Html.DisplayFor(model => model.Tutor.Staff.Person.LastName)
        </dt>
        <dd>
            
        </dd>
        <dt>
            <u>Students</u>

            @*<div class="form-group">

                <select class="form-control" asp-items="ViewBag.test"></select>
            </div>*@
        </dt>
        <dd>
            <table>
                @foreach (var j in Model.EnrollmentMusicClass)
                {
                    var parms = new Dictionary<string, string>
                    {
                        { "id1", j.EnrollmentId.ToString() },
                        { "id2", j.MusicClassId.ToString() }
                    };

                <tr>
                    <td>                        
                        @j.Enrollment.Student.Person.FirstName
                        @j.Enrollment.Student.Person.LastName 
                    </td> 
                </tr>
                 }
            </table>
</dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MusicClassId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SMMC/SMMC/Views/MusicClasses/Edit.cshtml
@model SMMC.Models.MusicClass

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit Class</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MusicClassId" />
            <div class="form-group">
                <label asp-for="TutorId" class="control-label">Tutor</label>
                <select asp-for="TutorId" class="form-control" asp-items="ViewBag.TutorId"></select>
                <span asp-validation-for="TutorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LessonTimeId" class="control-label">Lesson Time</label>
                <select asp-for="LessonTimeId" class="form-control" asp-items="ViewBag.LessonTimeId"></select>
                <span asp-validation-for="LessonTimeId" class="text-danger"></span>

                <input type="hidden" asp-for="StartDate" class="form-control" />

                <input type="hidden" asp-for="EndDate" class="form-control" />

                <dt>
                    <br />
                    <u>Students</u>


                </dt>
                <dd>
                    <table>
                        @foreach (var j in Model.EnrollmentMusicClass)
                        {
                            var parms = new Dictionary<string, string>
                                                        {
                                                            { "id1", j.EnrollmentId.ToString() },
                                                            { "id2", j.MusicClassId.ToString() }
                                                        };

                            <tr>
                                <td>

                                    @j.Enrollment.Student.Person.FirstName
                                    @j.Enrollment.Student.Person.LastName
                                </td>
                                <td></td>
                                <td>
                                    |
                                    <a asp-controller="MusicClasses"
                                       asp-action="DeleteStudent"
                                       asp-all-route-data="parms">
                                        Remove
                                    </a>
                                </td>

                            </tr>
                        }
                    </table>

                </dd>                
               
                

                    <a asp-controller="EnrollmentMusicClasses"
                       asp-action="AddStudent"
                       asp-route-id="@Model.MusicClassId">
                        Add new student
                    </a>

            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SMMC/SMMC/Views/MusicClasses/Index.cshtml
@model IEnumerable<SMMC.Models.EnrollmentMusicClass>

@{
    ViewData["Title"] = "Index";
}

<h2>Classes</h2>

<p>
   
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Start Date
            </th>
            <th>
                End Date
            </th>
            <th>
                Lesson Time
            </th>
            <th>
                Instrument
            </th>
            <th>
                Grade
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MusicClass.Tutor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.MusicClass.StartDate.ToShortDateString()
            </td>
            <td>
                @item.MusicClass.EndDate.ToShortDateString()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MusicClass.LessonTime.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Enrollment.Instrument.Instrument1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Enrollment.Grade)</td>
            <td>
                @Html.DisplayFor(modelItem => item.MusicClass.Tutor.Staff.Person.FirstName)
                @Html.DisplayFor(modelItem => item.MusicClass.Tutor.Staff.Person.LastName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MusicClassId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MusicClassId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MusicClassId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>